"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-13 17:18:38.341429

Autogenerated, then hand-edited:
- Postgres enum types are created once up front (record_status is shared by two tables)
  and dropped in downgrade.
- booking_reference_seq (used by bookings.reference default) is created/dropped explicitly.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateSequence, DropSequence

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

record_status = postgresql.ENUM('ACTIVE', 'INACTIVE', name='record_status', create_type=False)
slot_status = postgresql.ENUM('ACTIVE', 'INACTIVE', 'CANCELLED', name='slot_status', create_type=False)
user_role = postgresql.ENUM('USER', 'ADMIN', name='user_role', create_type=False)
booking_status = postgresql.ENUM(
    'PENDING', 'CONFIRMED', 'EXPIRED', 'FAILED', 'CANCELLED', 'COMPLETED', name='booking_status', create_type=False
)
payment_status = postgresql.ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='payment_status', create_type=False)
recipient_type = postgresql.ENUM('USER', 'ADMIN', name='recipient_type', create_type=False)
notification_type = postgresql.ENUM(
    'REGISTRATION', 'BOOKING_CONFIRMATION', 'ADMIN_PAYMENT', 'REMINDER', 'CANCELLATION', 'REFUND', 'PASSWORD_RESET',
    name='notification_type', create_type=False,
)
notification_channel = postgresql.ENUM('EMAIL', 'SMS', name='notification_channel', create_type=False)
notification_status = postgresql.ENUM(
    'PENDING', 'SENT', 'DELIVERED', 'FAILED', name='notification_status', create_type=False
)

ENUMS = [
    record_status, slot_status, user_role, booking_status, payment_status,
    recipient_type, notification_type, notification_channel, notification_status,
]

booking_reference_seq = sa.Sequence('booking_reference_seq', start=10001)


def upgrade() -> None:
    bind = op.get_bind()
    for enum in ENUMS:
        enum.create(bind, checkfirst=True)
    op.execute(CreateSequence(booking_reference_seq))

    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', record_status, server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('payment_events',
    sa.Column('razorpay_event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events')),
    sa.UniqueConstraint('razorpay_event_id', name=op.f('uq_payment_events_razorpay_event_id'))
    )
    op.create_table('reminder_rules',
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('send_time_local', sa.Time(), nullable=False),
    sa.Column('send_email', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('send_sms', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('offset_days >= 0', name=op.f('ck_reminder_rules_offset_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder_rules')),
    sa.UniqueConstraint('offset_days', name=op.f('uq_reminder_rules_offset_days'))
    )
    op.create_table('webinars',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructor', sa.String(length=120), nullable=True),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', record_status, server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_webinars_duration_positive')),
    sa.CheckConstraint('price_paise >= 0', name=op.f('ck_webinars_price_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webinars'))
    )
    op.create_table('slots',
    sa.Column('webinar_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('status', slot_status, server_default='ACTIVE', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_seats >= 0 AND available_seats <= capacity', name=op.f('ck_slots_seats_within_capacity')),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_slots_capacity_positive')),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_slots_end_after_start')),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinars.id'], name=op.f('fk_slots_webinar_id_webinars'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slots'))
    )
    op.create_index('ix_slots_webinar_id_start_at', 'slots', ['webinar_id', 'start_at'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', user_role, server_default='USER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('webinar_departments',
    sa.Column('webinar_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_webinar_departments_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinars.id'], name=op.f('fk_webinar_departments_webinar_id_webinars'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('webinar_id', 'department_id', name=op.f('pk_webinar_departments'))
    )
    op.create_table('bookings',
    sa.Column('reference', sa.String(length=20), server_default=sa.text("'SC-' || nextval('booking_reference_seq')"), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('webinar_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('status', booking_status, server_default='PENDING', nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_paise >= 0', name=op.f('ck_bookings_amount_non_negative')),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], name=op.f('fk_bookings_slot_id_slots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinars.id'], name=op.f('fk_bookings_webinar_id_webinars'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('reference', name=op.f('uq_bookings_reference'))
    )
    op.create_index(op.f('ix_bookings_slot_id'), 'bookings', ['slot_id'], unique=False)
    op.create_index('ix_bookings_status_expires_at', 'bookings', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index('uq_bookings_active_user_slot', 'bookings', ['user_id', 'slot_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED')"))
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('recipient_type', recipient_type, nullable=False),
    sa.Column('recipient_address', sa.String(length=254), nullable=False),
    sa.Column('type', notification_type, nullable=False),
    sa.Column('channel', notification_channel, nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', notification_status, server_default='PENDING', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('reminder_offset_days', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'REMINDER') = (reminder_offset_days IS NOT NULL)", name=op.f('ck_notifications_reminder_offset_matches_type')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_notifications_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_booking_id'), 'notifications', ['booking_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('uq_notifications_confirmation', 'notifications', ['booking_id', 'type', 'channel', 'recipient_address'], unique=True, postgresql_where=sa.text("type IN ('BOOKING_CONFIRMATION', 'ADMIN_PAYMENT')"))
    op.create_index('uq_notifications_reminder', 'notifications', ['booking_id', 'channel', 'recipient_address', 'reminder_offset_days'], unique=True, postgresql_where=sa.text("type = 'REMINDER'"))
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=256), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('status', payment_status, server_default='PENDING', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razorpay_refund_id', sa.String(length=64), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_paise >= 0', name=op.f('ck_payments_amount_non_negative')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('razorpay_order_id', name=op.f('uq_payments_razorpay_order_id')),
    sa.UniqueConstraint('razorpay_payment_id', name=op.f('uq_payments_razorpay_payment_id'))
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index('uq_payments_active_booking', 'payments', ['booking_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'PAID')"))


def downgrade() -> None:
    op.drop_index('uq_payments_active_booking', table_name='payments', postgresql_where=sa.text("status IN ('PENDING', 'PAID')"))
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('uq_notifications_reminder', table_name='notifications', postgresql_where=sa.text("type = 'REMINDER'"))
    op.drop_index('uq_notifications_confirmation', table_name='notifications', postgresql_where=sa.text("type IN ('BOOKING_CONFIRMATION', 'ADMIN_PAYMENT')"))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_booking_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('uq_bookings_active_user_slot', table_name='bookings', postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED')"))
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index('ix_bookings_status_expires_at', table_name='bookings')
    op.drop_index(op.f('ix_bookings_slot_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('webinar_departments')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_slots_webinar_id_start_at', table_name='slots')
    op.drop_table('slots')
    op.drop_table('webinars')
    op.drop_table('reminder_rules')
    op.drop_table('payment_events')
    op.drop_table('departments')

    op.execute(DropSequence(booking_reference_seq))
    bind = op.get_bind()
    for enum in reversed(ENUMS):
        enum.drop(bind, checkfirst=True)
